#!/bin/bash
snmpwalk -v2c -c redhat localhost system >/home/joro/log.txt 2>&1
resolt1=`cat /home/joro/log.txt`
resolt="Timeout: No Response from localhost"
if [ "$resolt1" = "$resolt" ]
then
service snmpd start
else 
echo "Snmpd is running"
fi
